import Head from 'next/head';
import './globals.css';
import 'mapbox-gl/dist/mapbox-gl.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <title>Prjkt:Hawk</title>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css"
          rel="stylesheet"
        />
        <meta
          name="viewport"
          content="initial-scale=1,maximum-scale=1,user-scalable=no"
        ></meta>
      </Head>

      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
